version: '3'
services:
  postgres:
    image: postgres:13.3
    restart: always
    environment:
      POSTGRES_USER: "qazdi"
      POSTGRES_PASSWORD: "admin"
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
    driver: local
